services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXTAUTH_SECRET=114514
      - FINNHUB_API_KEY=d4kus89r01qt7v17drf0d4kus89r01qt7v17drfg
      - DATABASE_URL=mysql://webapp:1145141919810@db:3306/mydb
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - ../:/app
    depends_on:
      - db
  db: # 服務名稱，可自訂
    image: mysql:8.0 # MySQL 版本
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1145141919810 # 根密碼，自訂
      - MYSQL_DATABASE=mydb # 預設資料庫名，自訂
      - MYSQL_USER=webapp # 可選：新增使用者
      - MYSQL_PASSWORD=1145141919810 # 可選：使用者密碼
    volumes:
      - db:/var/lib/mysql # 持久化資料
volumes:
  db: # 命名 volume
